In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=42)

kfold = KFold(n_splits=5)
cv_accuracy = []
print(features.shape[0])

150


In [33]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(n_iter, accuracy, train_size, test_size)
    cv_accuracy.append(accuracy)

print(np.mean(cv_accuracy))

1 1.0 120 30
2 1.0 120 30
3 0.8333 120 30
4 0.9333 120 30
5 0.8 120 30
0.91332


In [34]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
print(encoder.classes_)

[0 1 4 2 2 3 3]
['TV' '냉장고' '선풍기' '에어컨' '컴퓨터']


In [36]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨']

items = np.array(items).reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(7, 5)


In [39]:
import pandas as pd

df = pd.DataFrame(['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '에어컨', '에어컨'])
print(df)
pd.get_dummies(df)

     0
0   TV
1  냉장고
2  컴퓨터
3  선풍기
4  선풍기
5  에어컨
6  에어컨


,0_TV,0_냉장고,0_선풍기,0_에어컨,0_컴퓨터
0,True,False,False,False,False
1,False,True,False,False,False
2,False,False,False,False,True
3,False,False,True,False,False
4,False,False,True,False,False
5,False,False,False,True,False
6,False,False,False,True,False
